---
- hosts: 127.0.0.1
  become: yes
  tasks:
  - name: "Install nginx via apt"
    ansible.builtin.apt:
      name: "nginx"
      state: "latest"

  - name: deploying server
    local_action: command bash /ansible/deploy_web_server.sh
...