all:
  hosts:
    nginx_container:
      ansible_host: 172.17.0.2
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: docker
    # ansible_ssh_private_key_file: /home/roman/.ssh/id_rsa