version: '3.8'

services:
  ansible:
    build: ansible/
    depends_on:
      - app
    networks:
      my_net:
        ipv4_address: 10.5.0.5
  
  app:
    build: web_server/
    ports:
      - 80:80
    networks:
      my_net:
        ipv4_address: 10.5.0.6

networks:
  my_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
